import assert from 'node:assert/strict';
import { csv, recordFrom, parseBatch, normalizeDimensions, exportRecords } from './logic.ts';
import { FIXTURES, SAMPLE, PREVIEW } from './fixtures.ts';
assert.equal(FIXTURES.length, 30);
assert.equal(FIXTURES.filter(f => f.heldOut).length, 10);
assert.equal(PREVIEW.filter(r => r.issues.length).length, 1);
assert.deepEqual(PREVIEW[3].issues, ['Missing material', 'Missing size']);
const make = (data, probability = 1) => recordFrom('Red cotton shirt, size M.', { label: 'apparel', probability }, { data });
assert.equal(make({ material: 'cotton', size: 'M', color: 'Red' }).issues.length, 0);
assert(make({ material: 'silk', size: 'M', color: 'Red' }).issues.includes('Missing material'));
assert.equal(make({ material: 'silk' }).attributes.material, undefined);
assert(make({ material: [], size: 'M', color: 'Red' }).issues.includes('material: unexpected value type'));
assert(make({ material: 'cotton', size: 'M', color: 'Red' }, .6).issues.some(i => i.includes('threshold')));
assert.throws(() => recordFrom('x', { label: '__proto__', probability: 1 }, { data: {} }));
assert.throws(() => parseBatch(['x'], { results: [] }, { results: [] }));
assert.equal(normalizeDimensions('48 x 24 x 30 inches'), '121.92 × 60.96 × 76.2 cm');
assert.equal(normalizeDimensions('400 × 500 mm'), '40 × 50 cm');
assert.equal(normalizeDimensions('45 cm x 20 inches'), undefined);
assert.equal(normalizeDimensions('12 feet'), undefined);
for (const text of ['=1+2', ' +SUM(A1)', '\n@HYPERLINK("bad")', '-2']) assert(csv([{ source: text }]).includes('"\''));
const exports = exportRecords(SAMPLE, PREVIEW, true);
assert.equal(exports[0].provenance, 'sample preview');
assert.equal(exports[3].size, null);
assert.equal(exports[0].source, SAMPLE[0]);
for (const [index, record] of PREVIEW.entries()) for (const attribute of Object.values(record.attributes)) assert.equal(SAMPLE[index].slice(attribute.start, attribute.end), attribute.value);
console.log('Catalog checks passed: required fields, source matching, malformed responses, review thresholds, unit conversion, safe exports and 30 labelled fixtures.');

const unicode = recordFrom('İ. Cotton shirt.', { label: 'apparel', probability: 1 }, { data: { material: 'cotton' } });
assert.equal(unicode.attributes.material, undefined, 'Unsafe case-folded offsets must never highlight the wrong source');
const exactUnicode = recordFrom('İ. cotton shirt.', { label: 'apparel', probability: 1 }, { data: { material: 'cotton' } });
assert.equal(exactUnicode.attributes.material.start, 3);
