import assert from 'node:assert/strict';
import { parseFindings, literalFindings, redact, mergedRanges, SAMPLE, SAMPLE_FINDINGS } from './logic.ts';
const entity = (text, start, end, type = 'person') => ({ text, start, end, type, probability: .1 });
assert.equal(redact(SAMPLE, SAMPLE_FINDINGS).includes('maya.chen@example.com'), false);
assert.equal((redact(SAMPLE, SAMPLE_FINDINGS).match(/\[REDACTED\]/g) || []).length, 4);
const unicode = '🙂 Customer: Zoë Martin. Email zoe@example.com. Account AC-7781.';
const parsed = parseFindings(unicode, {entities: [entity('Zoë Martin', 12, 22), entity('zoe@example.com',30,45,'email'),entity('AC-7781',55,62,'account_id')]});
assert.equal(parsed.rejected, 0);
assert.equal(parsed.findings[0].start, 13);
assert.equal(redact(unicode,parsed.findings),'🙂 Customer: [REDACTED]. Email [REDACTED]. Account [REDACTED].');
assert.equal(parsed.findings.length, 3, 'Low confidence is never silently excluded');
const duplicated = parseFindings('Ann Ann', {entities:[entity('Ann',0,3),entity('Ann',4,7),entity('Ann',0,3)]});
assert.equal(duplicated.findings.length,2);
assert.equal(redact('Ann Ann',duplicated.findings),'[REDACTED] [REDACTED]');
const overlap = [...literalFindings('ABABABA','ABA'), ...literalFindings('ABABABA','BAB')];
assert.deepEqual(mergedRanges('ABABABA',overlap),[{start:0,end:7}]);
assert.equal(redact('ABABABA',overlap),'[REDACTED]');
assert.equal(redact('abc def',[...literalFindings('abc def','abc'),...literalFindings('abc def','c d')]),'[REDACTED]ef');
assert.deepEqual(literalFindings('a.b aXb','a.b').map(f=>f.text),['a.b']);
assert.deepEqual(literalFindings('No match',''),[]);
assert.equal(redact('changed source',SAMPLE_FINDINGS),'changed source','Stale offsets cannot redact edited source');
assert.equal(parseFindings('Nothing here',{entities:[]}).findings.length,0);
assert.equal(parseFindings('Ann',{entities:[entity('Ann',1,4),entity('other',0,3),entity('Ann',-1,3),entity('Ann',0,3,'__proto__'),{...entity('Ann',0,3),probability:2},null]}).rejected,6);
assert.throws(()=>parseFindings('Ann',{entities:null}));
assert.equal(redact('<script>Ann</script>',literalFindings('<script>Ann</script>','Ann')),'<script>[REDACTED]</script>');
console.log('Private Share: 16 logic checks passed (Unicode, repeats, overlap, stale offsets, malformed data, literal masking).');
