import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || '/Users/blaget/.agents/skills/gstack/node_modules/playwright/index.mjs');
const base = process.env.QA_BASE || 'http://127.0.0.1:4335';
const out = process.env.QA_OUTPUT || '/tmp/ms-build-private-share-qa';
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
let calls=0, behavior='normal';
await page.addInitScript(()=>localStorage.setItem('ms.apiKey','sk-ms-ui-test-not-a-real-credential'));
await page.route('**/api/run',async route=>{
  calls++;
  const {body}=route.request().postDataJSON();
  if(behavior==='delay') await new Promise(r=>setTimeout(r,1200));
  if(behavior==='error'){await route.fulfill({status:500,json:{error:{message:'Test service unavailable'}}});return;}
  const text=body.text, names=['Maya Chen','maya.chen@example.com','NW-2048','+1 202 555 0148'];
  const types=['person','email','account_id','phone'];
  const entities=names.flatMap((name,i)=>{const ix=text.indexOf(name);if(ix<0)return [];const start=[...text.slice(0,ix)].length;return [{text:name,type:types[i],start,end:start+[...name].length,probability:.99}];});
  await route.fulfill({status:200,headers:{'x-input-tokens':'132','x-inference-ms':'14'},json:{entities}}).catch(()=>{});
});
await page.goto(`${base}/private-share/`);
await page.getByText('Sample preview · curated selections, no API calls').waitFor();
assert.equal(calls,0);
assert.equal(await page.getByTestId('source-highlight').locator('mark').count(),4);
await page.screenshot({path:`${out}/desktop.png`,fullPage:true});
await page.getByRole('checkbox',{name:/Name Maya Chen/}).uncheck();
assert.match(await page.getByTestId('redaction-preview').innerText(),/Maya Chen/);
await page.getByLabel('Missed something? Add exact text to remove.').fill('last month');
await page.getByRole('button',{name:'Redact all matches'}).click();
assert.doesNotMatch(await page.getByTestId('redaction-preview').innerText(),/last month/);
await page.getByRole('button',{name:'Edit transcript'}).click();
await page.getByLabel('Transcript',{exact:true}).fill('🙂 Customer: Maya Chen. My email is maya.chen@example.com.');
assert.equal(await page.getByRole('button',{name:'Copy preview',exact:true}).isDisabled(),true);
await page.getByRole('button',{name:'Detect details live'}).click();
await page.getByText('2 model findings · review the entire transcript').waitFor();
assert.equal(calls,1);
assert.equal(await page.getByTestId('source-highlight').locator('mark').first().innerText(),'Maya Chen');
await page.getByRole('checkbox',{name:'I reviewed the full transcript and the remaining visible details.'}).check();
assert.equal(await page.getByRole('button',{name:'Copy preview',exact:true}).isEnabled(),true);
await page.getByRole('checkbox',{name:/Name.*Maya Chen/}).uncheck();
assert.equal(await page.getByRole('button',{name:'Copy preview',exact:true}).isDisabled(),true);
behavior='error';
await page.getByRole('button',{name:'Detect details live'}).click();
await page.getByRole('alert').waitFor();
assert.equal(await page.getByRole('button',{name:'Copy preview',exact:true}).isDisabled(),true);
behavior='normal';
await page.getByRole('button',{name:'Detect details live'}).click();
await page.getByText('2 model findings · review the entire transcript').waitFor();
assert.equal(await page.getByRole('alert').count(),0);
behavior='delay';
await Promise.all([page.waitForRequest('**/api/run'),page.getByRole('button',{name:'Detect details live'}).click()]);
await page.getByRole('button',{name:'Stop detection'}).click();
await page.waitForTimeout(1500);
assert.match(await page.locator('.ps-status').innerText(),/Detection stopped/);
assert.equal(await page.getByTestId('source-highlight').locator('mark').count(),0);
await Promise.all([page.waitForRequest('**/api/run'),page.getByRole('button',{name:'Detect details live'}).click()]);
await page.getByRole('button',{name:'Edit transcript'}).click();
await page.getByLabel('Transcript',{exact:true}).fill('Edited while running.');
await page.waitForTimeout(1500);
assert.match(await page.locator('.ps-status').innerText(),/Edited transcript · not yet checked by the model/);
assert.equal(await page.getByTestId('redaction-preview').innerText(),'Your preview starts with a review\n\nRun detection or add an exact phrase below. Previous results are cleared whenever you edit the source.');
await page.getByRole('button',{name:'Load sample'}).click();
await page.getByRole('checkbox',{name:'I reviewed the full transcript and the remaining visible details.'}).check();
const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download .txt'}).click()]);
assert.equal(await readFile(await download.path(),'utf8'),await page.getByTestId('redaction-preview').innerText());
await page.setViewportSize({width:390,height:844});
await page.reload();
await page.getByText('Sample preview · curated selections, no API calls').waitFor();
await page.locator('body').click({position:{x:2,y:2}});
await page.screenshot({path:`${out}/mobile.png`,fullPage:true});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.getByRole('button',{name:'Edit transcript'}).click();
await page.getByLabel('Transcript',{exact:true}).fill('<script>alert(1)</script>');
await page.getByRole('button',{name:'View source'}).click();
assert.match(await page.getByTestId('source-highlight').innerText(),/<script>/);
await browser.close();
console.log(`Private Share browser checks passed: sample, selections, manual edit, Unicode, input invalidation, error/retry, cancellation, late-result protection, mobile overflow, literal rendering. ${calls} mock requests.`);
