// Deterministic UI verification; no live API requests.
// PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node src/demos/returns-desk/browser-check.mjs
import assert from "node:assert/strict";
import fs from "node:fs/promises";
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || "playwright");
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
let calls = 0, delayed = false, fail = false;
const output = process.env.QA_OUTPUT || "/tmp/ms-build-returns-desk-qa";
await fs.mkdir(output, { recursive: true });
const errors = [];
page.on("pageerror", e => errors.push(e.message));
await page.route("**/api/run", async route => {
  calls++;
  if (delayed) await new Promise(r => setTimeout(r, 800));
  if (fail) return route.fulfill({ status: 500, contentType: "application/json", body: JSON.stringify({ error: { message: "Test transport failure", code: "test" } }) }).catch(() => {});
  const { route: kind, body } = route.request().postDataJSON();
  const id = /RD-\d+/.exec(body.text)?.[0] || null;
  const data = kind === "classify" ? { label: "return_or_exchange", probability: .99 } : { results: [{ answer: id, start: id ? body.text.indexOf(id) : null, end: id ? body.text.indexOf(id) + id.length : null }] };
  await route.fulfill({ status: 200, headers: { "content-type": "application/json", "x-input-tokens": "100", "x-inference-ms": "20" }, body: JSON.stringify(data) }).catch(() => {});
});
await page.goto((process.env.QA_BASE || "http://127.0.0.1:4336") + "/returns-desk/");
await page.getByTestId("return-route").waitFor();
assert.equal(calls, 0, "sample must make zero API calls");
assert.equal(await page.getByTestId("return-route").innerText(), "Standard handling");
await page.screenshot({ path: output + "/desktop.png", fullPage: true });
await page.getByRole("button", { name: "Outside the window", exact: true }).click();
assert.equal(await page.getByTestId("return-route").innerText(), "Exception review");
await page.getByRole("button", { name: "Missing facts", exact: true }).click();
assert.equal(await page.getByTestId("return-route").innerText(), "Missing information");
await page.getByRole("button", { name: "Order mismatch", exact: true }).click();
assert.equal(await page.getByTestId("return-route").innerText(), "Exception review");
assert.equal(calls, 0, "switching previews must not call the API");
await page.getByRole("button", { name: "Routine return", exact: true }).click();
await page.getByRole("button", { name: /View order evidence/ }).click();
assert.equal(await page.locator(".rd-source mark").innerText(), "RD-1042");
await page.getByLabel("Order value (USD)", { exact: true }).fill("150.01");
assert.equal(await page.getByTestId("return-route").count(), 0, "edits clear stale result");
await page.evaluate(() => localStorage.setItem("ms.apiKey", "sk-ms-ui-test-0000000000000000000000"));
await page.getByRole("button", { name: "Check request live", exact: true }).click();
await page.getByTestId("return-route").waitFor();
assert.equal(await page.getByTestId("return-route").innerText(), "Exception review");
assert.equal(calls, 2, "one complete run uses two requests");
await page.getByRole("button", { name: "Routine return", exact: true }).click();
delayed = true;
const beforeCancel = calls;
await page.getByRole("button", { name: "Check request live", exact: true }).click();
assert.equal(await page.getByRole("button", { name: "Check request live", exact: true }).isDisabled(), true);
for (let i = 0; i < 30 && calls === beforeCancel; i++) await page.waitForTimeout(50);
assert.equal(calls, beforeCancel + 1, "cancel while the classification response is in flight");
await page.getByRole("button", { name: "Stop", exact: true }).click();
await page.waitForTimeout(1000);
assert.equal(await page.getByTestId("return-route").count(), 0, "late result after cancellation cannot create a route");
assert.match(await page.locator(".rd-status").innerText(), /Stopped/);
delayed = false; fail = true;
await page.getByRole("button", { name: "Check request live", exact: true }).click();
await page.getByRole("button", { name: "Retry live check", exact: true }).waitFor();
assert.equal(await page.getByTestId("return-route").count(), 0);
fail = false;
await page.getByRole("button", { name: "Retry live check", exact: true }).click();
await page.getByTestId("return-route").waitFor();
assert.equal(await page.getByTestId("return-route").innerText(), "Standard handling");
await page.screenshot({ path: output + "/desktop-live.png", fullPage: true });
await page.setViewportSize({ width: 390, height: 844 });
await page.reload();
await page.getByTestId("return-route").waitFor();
await page.getByRole("button", { name: "Order mismatch", exact: true }).click();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "no mobile horizontal overflow");
await page.screenshot({ path: output + "/mobile.png", fullPage: true });
await page.getByText("Build this workflow", { exact: true }).click();
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, "expanded code has no mobile overflow");
assert.deepEqual(errors, []);
await browser.close();
console.log("Browser checks passed: previews, routing, evidence, invalidation, cancellation, retry, mobile overflow.");
