// node scripts/generate-receipt.mjs — regenerates the stock receipt image checked in at
// src/demos/receipt-reader/receipt.ts. Same satori + resvg pair as the social cards (src/lib/og.ts).
// The image is committed because its bytes are part of the stock request digest: regenerating it
// changes the example ID, so run this only when the receipt itself must change.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { Resvg } from '@resvg/resvg-js';
import satori from 'satori';

const require = createRequire(import.meta.url);
const font = (weight) => ({ name: 'Space', weight, style: 'normal', data: readFileSync(require.resolve(`@fontsource/space-grotesk/files/space-grotesk-latin-${weight}-normal.woff`)) });
const WIDTH = 420, HEIGHT = 620;
const el = (type, style, children) => ({ type, props: { style, children } });
const row = (left, right, style = {}) => el('div', { display: 'flex', justifyContent: 'space-between', fontSize: 15, ...style }, [el('span', { display: 'flex' }, left), el('span', { display: 'flex' }, right)]);
const items = [
  ['2 Flat white', '9.00'],
  ['1 Almond croissant', '4.25'],
  ['1 Sourdough loaf', '7.50'],
  ['1 Oat milk 1L', '3.10'],
];
const tree = el('div', { width: WIDTH, height: HEIGHT, display: 'flex', flexDirection: 'column', gap: 10, padding: '28px 30px', backgroundColor: '#fbfaf7', color: '#191919', fontFamily: 'Space' }, [
  el('div', { fontSize: 24, fontWeight: 700, letterSpacing: '-0.03em' }, 'HARBOR LANE BAKERY'),
  el('div', { fontSize: 14, color: '#5c5a57' }, '18 Quay Street, Wellport'),
  el('div', { fontSize: 14, color: '#5c5a57' }, 'VAT 4471 882 10'),
  el('div', { height: 1, backgroundColor: '#c9c5bd', marginTop: 8, marginBottom: 8 }),
  row('Receipt', 'HLB-40218'),
  row('Date', '2026-09-18  08:42'),
  row('Server', 'Ana K.'),
  el('div', { height: 1, backgroundColor: '#c9c5bd', marginTop: 8, marginBottom: 8 }),
  ...items.map(([name, price]) => row(name, price)),
  el('div', { height: 1, backgroundColor: '#c9c5bd', marginTop: 8, marginBottom: 8 }),
  row('Subtotal', '23.85'),
  row('Tax 8%', '1.91'),
  row('TOTAL', 'USD 25.76', { fontSize: 20, fontWeight: 700, marginTop: 6 }),
  el('div', { height: 1, backgroundColor: '#c9c5bd', marginTop: 8, marginBottom: 8 }),
  row('Card', 'VISA ****4417'),
  row('Auth', '021884'),
  el('div', { fontSize: 13, color: '#5c5a57', marginTop: 12 }, 'Thank you. Fictional receipt, no real business.'),
]);

const svg = await satori(tree, { width: WIDTH, height: HEIGHT, fonts: [font(400), font(700)] });
const png = new Resvg(svg, { fitTo: { mode: 'width', value: WIDTH } }).render().asPng();
const file = new URL('../src/demos/receipt-reader/receipt.ts', import.meta.url);
writeFileSync(file, `// Generated by scripts/generate-receipt.mjs. A fictional receipt; regenerating it changes the stock example ID.\nexport const RECEIPT = {\n  width: ${WIDTH},\n  height: ${HEIGHT},\n  alt: 'Fictional Harbor Lane Bakery receipt: four items, subtotal 23.85, tax 1.91, total USD 25.76.',\n  dataUrl: 'data:image/png;base64,${Buffer.from(png).toString('base64')}',\n};\n`);
console.log(`Receipt: ${WIDTH}x${HEIGHT}, ${(png.length / 1024).toFixed(1)} kB PNG, ${(Buffer.from(png).toString('base64').length / 1024).toFixed(1)} kB base64.`);
