#!/usr/bin/env python3
"""Regenerate small embedded samples from original dataset archives (requires Pillow).
Usage: python3 scripts/source-leaf-land.py /path/to/ibeans-test.zip /path/to/EuroSAT_RGB.zip
Download links, archive checksums and licenses are recorded beside each dataset.
"""
import base64
import hashlib
import io
import json
from pathlib import Path
import sys
from urllib.parse import quote
import zipfile
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
LEAF_ARCHIVE = 'https://huggingface.co/datasets/AI-Lab-Makerere/beans/resolve/main/data/test.zip'
LAND_ARCHIVE = 'https://zenodo.org/records/7711810/files/EuroSAT_RGB.zip'
LAND_CLASSES = {
    'AnnualCrop': 'Annual crop', 'Forest': 'Forest',
    'HerbaceousVegetation': 'Herbaceous vegetation', 'Highway': 'Highway',
    'Industrial': 'Industrial', 'Pasture': 'Pasture',
    'PermanentCrop': 'Permanent crop', 'Residential': 'Residential',
    'River': 'River', 'SeaLake': 'Sea or lake',
}


def write_samples(slug, archive_path, source, selection, shrink):
    archive = zipfile.ZipFile(archive_path)
    samples, provenance = [], []
    for path, label, number in selection:
        original = archive.read(path)
        im = Image.open(io.BytesIO(original))
        original_size = im.size
        if shrink:
            im = im.convert('RGB')
            im.thumbnail((448, 448), Image.Resampling.LANCZOS)
            encoded = io.BytesIO()
            im.save(encoded, 'JPEG', quality=70, optimize=True)
            data = encoded.getvalue()
        else:
            data = original
        assert max(im.size) <= 512 and len(data) < 60_000
        filename = Path(path).name
        identifier = filename.removesuffix('.jpg').replace('_', '-').replace('.', '-')
        samples.append({
            'id': identifier, 'caption': f'{label} · {number}' if shrink else label,
            'alt': f'Bean leaf field photograph, dataset category {label.lower()}, sample {number}' if shrink else f'Sentinel-2 RGB satellite tile, EuroSAT category {label.lower()}, 64 by 64 pixels',
            'expected': label, 'width': im.width, 'height': im.height,
            'dataUrl': 'data:image/jpeg;base64,' + base64.b64encode(data).decode(),
            'sourceUrl': source + '#' + quote(path, safe='/'),
        })
        provenance.append({'id': identifier, 'archivePath': path, 'originalWidth': original_size[0], 'originalHeight': original_size[1], 'originalSha256': hashlib.sha256(original).hexdigest(), 'embeddedSha256': hashlib.sha256(data).hexdigest()})
    destination = ROOT / 'src/demos' / slug
    (destination / 'samples.ts').write_text('// Generated by scripts/source-leaf-land.py. Original filenames and hashes: provenance.json.\nimport type { ImageSample } from "../../lib/image-demo.ts";\n\nexport const samples: ImageSample[] = ' + json.dumps(samples, indent=2) + ';\n')
    (destination / 'provenance.json').write_text(json.dumps({'archiveUrl': source, 'archiveSha256': hashlib.sha256(Path(archive_path).read_bytes()).hexdigest(), 'transformation': 'Aspect-preserving downsample to at most 448 px; JPEG quality 70. No crops or retouching.' if shrink else 'Original 64 by 64 RGB JPEG bytes, unchanged.', 'files': provenance}, indent=2) + '\n')
    print(f'{slug}: {len(samples)} original dataset images verified')


if __name__ == '__main__':
    leaf = [(f'test/{c}/{c}_test.{i}.jpg', label, i + 1) for c, label in [('healthy', 'Healthy'), ('angular_leaf_spot', 'Angular leaf spot'), ('bean_rust', 'Bean rust')] for i in range(3)]
    land = [(f'EuroSAT_RGB/{c}/{c}_1.jpg', label, 1) for c, label in LAND_CLASSES.items()]
    write_samples('leaf-check', sys.argv[1], LEAF_ARCHIVE, leaf, True)
    write_samples('land-cover', sys.argv[2], LAND_ARCHIVE, land, False)
